---
testing: true # If true MQTT topics prefixed with TEST/
poll_rate: 12 # Rate (time in seconds) at which to poll for data
log_level: DEBUG
pwrcell:
  ssh_tunnel:
    host: 127.0.0.1
    identity_file: /Users/example/.ssh/pwrcell
  device_ids: # Get these IDs by running `python scan.py`
    rebus_beacon: 1
    inverter: 8
    battery: 9
    pv_links: [3, 4, 5, 6, 7]
mqtt:
  client_name: pwrcell-ha
  host: homeassistant
  port: 1883
  username: mqtt-pwrcell
  password: hunter2
